### PR TITLE
Add Travis CI support

### PR DESCRIPTION
**Pull request by elyscape**
Issue #129 surfaced recently as a result of insufficient testing.  This PR adds automated testing with [Travis CI](https://travis-ci.org/) to help avoid similar issues in the future.  Once enabled, Travis integrates with GitHub and will display the build status on PRs.  It's very convenient.

Some notes:

1. Some of the builds currently fail.  This is because of bugs in highline or the tests that will need to be fixed.
2. @JEG2 will need to activate Travis builds for this repository at the Travis CI website.  I would recommend doing this before merging this PR.

### CODE REVIEW

**Comment by JEG2** [comment]
Seems like a great idea to me.

**Comment by elyscape** [comment]
@JEG2 You can trigger an initial build without pushing any commits to the repo by going to [your repository webhook settings](https://github.com/JEG2/highline/settings/hooks), clicking "Travis CI", and hitting the "Test service" button in the upper right corner of the page that loads.

**Comment by JEG2** [comment]
Done.

**Comment by elyscape** [comment]
@JEG2 For some reason it looks like Travis hasn't picked up on it.  You made sure to enable Travis for that repo [on your Travis profile page](https://travis-ci.org/profile/JEG2), right?

**Comment by abinoam** [comment]
Great to have Travis CI support 
:+1: @elyscape

**Comment by abinoam** [comment]
CI worked fine on my fork.
https://travis-ci.org/abinoam/highline

The IO/console bug is easy to fix (I guess).
The other, is a test on YAML, and YAML previous versions are buggy. (See #69 and PR #124).

Should we "conditionally" test this?

**Comment by JEG2** [comment]
Travis support should be fixed now.

**Pull request merged**
