### PR TITLE
DRY style definitions

### PR DESCRIPTION
**Pull request by matugm**
I noticed a pattern where `builtin: true` was repeated many times. I came up with this refactoring to make the code more DRY. What do you think?

### CODE REVIEW

**Comment by abinoam** [comment]
Hi @matugm 

Great catch! Thanks!

I have just 2 small suggestions.
1) Could you fix the indentation on the 
```ruby
    COLORS = {
      black:	 { code: "\e[30m", rgb: [0, 0, 0] },
      red:	   { code: "\e[31m", rgb: [128, 0, 0] },
      green:	 { code: "\e[32m", rgb: [0, 128, 0] },
      blue:	   { code: "\e[34m", rgb: [0, 0, 128] },
      yellow:	 { code: "\e[33m", rgb: [128, 128, 0] },
      magenta: { code: "\e[35m", rgb: [128, 0, 128] },
      cyan:	   { code: "\e[36m", rgb: [0, 128, 128] },
      white:	 { code: "\e[37m", rgb: [192, 192, 192] },
      gray:	   { code: "\e[37m", rgb: [192, 192, 192] },
      grey:	   { code: "\e[37m", rgb: [192, 192, 192] },
      none:	   { code: "\e[38m", rgb: [0, 0, 0] }
    }
```

We prefer 2 spaces instead of tabs. (although I think there's some tabs lying around the code waiting to be removed).

2) I personally prefer to split the commits to contain "only" close related code changes.
So parts like:
```diff
-          if suffix
-            style
-          else
-            style.code
-          end
+
+          suffix ? style : style.code
```

... could perfectly be in a separate commit for itself.

As soon as you fix the identation (remove and use 2 spaces instead) we can merge your code into master.

**Comment by abinoam** [comment]
Dear @JEG2 ,

I'd like to introduce you @matugm (Jesus Castello).
I have met him some weeks ago at Ruby Monday (codenewbie).
He is interested in refactoring and code quality.
In a private talk he showed interest in contributing to HighLine.

Welcome aboard @matugm!

**Comment by JEG2** [comment]
Another programmer that likes pain??? :stuck_out_tongue_winking_eye: 

Seriously, welcome @matugm!

**Comment by abinoam** [comment]
No pain no gain :stuck_out_tongue_winking_eye:

**Comment by abinoam** [comment]
Thanks @matugm !

**Comment by matugm** [comment]
@JEG2 Thank you :)

**Pull request merged**
