### PR TITLE
Prepare for V1.7.0 release

### PR DESCRIPTION
**Pull request by abinoam**
Related to #126 and #127

### CODE REVIEW

**Comment by abinoam** [comment]
I've created a tag v1.7.0! Ok?

**Comment by abinoam** [comment]
And... I think "rake release" should work for uploading it to Rubygems.

**Comment by JEG2** [comment]
[Done.](https://rubygems.org/gems/highline)

**Comment by abinoam** [comment]
Fast! 

Have "rake release" worked well?

I mean... rake release and ready!?!?

**Comment by JEG2** [comment]
I used `rake release`.  It was perfect!  Thank you so, so much.

**Comment by abinoam** [comment]
Great!!!

**Pull request merged**
