### PR TITLE
Update travis build matrix

### PR DESCRIPTION
**Pull request by abinoam**

### CODE REVIEW

**Comment by AlexWayfer** [comment]
Travis integration is outdated for GitHub, as I know. A lot of CIs moved to another type of integration, and I'd recommend switch CI too.

**Comment by abinoam** [comment]
Thanks for the feedback @AlexWayfer 

With the Ruby 3.2 release I was trying to experiment with the travis build to include 3.2 and recheck the others.

What is the new "standard" CI service for opensource ruby gems?

**Comment by abinoam** [comment]
I'll give GitHub actions a try. But I've never did it before.

**Comment by abinoam** [comment]
I'll be messing with it in my fork. https://github.com/abinoam/highline/actions/runs/3802354090

**Comment by AlexWayfer** [comment]
There are different ones. GitHub Actions are common. CircleCI is one of popular (RuboCop may use it). I love Cirrus CI. Not a lot of mater, just Travis is kind of outdated, you even can't see its results here, in the PR.

**Pull request closed without merging**
