### PR TITLE
Rebased PR #184 (original by @matrinox)

### PR DESCRIPTION
**Pull request by abinoam**
Hi @matrinox,

I have rebased your branch to remove the comes forth and goes back.

I removed that last commit that sacrifices the ability to pass a MenuItem directly. Looking more carefully I think your previous version was better (and my suggestions only messed things).

I'll merge this rebased version ok?

### CODE REVIEW

**Comment by abinoam** [comment]
cc #184

**Comment by matrinox** [comment]
I added a few more commits, up to a118d10. If you like them add it here and then we can merge!

**Comment by abinoam** [comment]
Hi @matrinox, I have just cherry picked your last commits and made some small adjustments. 

But I'm finding strange that GitHub is not respecting the commit order/sorting of my commit history. Just trying to fix this minor issue.

**Comment by abinoam** [comment]
https://help.github.com/articles/why-are-my-commits-in-the-wrong-order/

**Comment by abinoam** [comment]
Well, just tested from another computer and commits are in proper order/sorting.

**Comment by abinoam** [comment]
Dear @matrinox,

Thank you very much for your PR and the discussions we've had. Sorry for not being as fast to answer your comments as you deserve. And we hope you keep contributing to HighLine.

Merging into master!

cc: @JEG2 I think we're ready to release 2.0.0.develop.6 version (I have already updated VERSION).

**Comment by matrinox** [comment]
:+1:

**Comment by JEG2** [comment]
Release made.  I'm excited.  :smile:

**Pull request merged**
