### PR TITLE
Issue #138

### PR DESCRIPTION
**Pull request by abinoam**
Related to #138 

As a fast fix I just reapplied the commit and bumped up the version.

@KrauseFx, could you check if this fix for you before @JEG2 makes a new release?
(I'm not able to reproduce neither the fail nor the fix by now).

### CODE REVIEW

**Comment by KrauseFx** [comment]
Thanks for the quick fix!

Sorry, I somehow can't install the version from the `issue_138` branch, I cloned and ran `bundle install && sudo rake install`. Installation works fine, but as soon as a import `commander` the following is shown:

```
/Users/felixkrause/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- highline/import (LoadError)
```

The same in `irb`:
```sh
$ irb
> require 'highline'
LoadError: cannot load such file -- highline
	from /Users/felixkrause/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

If I do a `gem install highline` to install the last official release the `require` is working fine.

**Comment by abinoam** [comment]
Hi @KrauseFx , 

Try ```rake install``` without sudo.

Perhaps the use of sudo here could try to install the gem into a __multi user__ rvm install (at /usr/local/rvm, not at ~/.rvm). Not sure. (https://rvm.io/rvm/install)

Any way, I have managed to test it over here with...

```ruby -e "require 'commander'; ask('hi therehi therehi therehi therehi therehi therehi therehi therehi therehi therehi therehi therehi therehi therehi there')"```

... against the 2 versions.

I think is safe for @JEG2 to merge now.

And thanks for reporting the issue.

**Comment by JEG2** [comment]
I'll make a release if @KrauseFx reports this is working…

**Comment by KrauseFx** [comment]
@abinoam Thanks for the quick fix
@JEG2 Sorry it took so long, but I finally got the gem working. It's working fine and solves the problem :+1: 

Thank you for you help!

**Comment by JEG2** [comment]
I just released the fix.

**Comment by KrauseFx** [comment]
Thank you @JEG2, really appreciated :+1:

**Pull request merged**
