### PR TITLE
Extract QuestionAsker class

### PR DESCRIPTION
**Pull request by matugm**
Tried to isolate the logic about asking questions.

### CODE REVIEW

**Comment by abinoam** [comment]
Hi @matugm ,

Congratulations!!! Great PR! Really liked it. 
It's aligned with what I'm trying to accomplish here. 
Thank you very much.

I have just made some suggestions at each commit.
I'll wait for your feedback about them so we can discuss and merge it.
And I think @JEG2 can give his opinions too!

**Comment by abinoam** [comment]
@matugm I think we're ready for merging it.

@JEG2 , any comments?

**Comment by JEG2** [comment]
At Strange Loop.  Give me time.

**Comment by abinoam** [comment]
@JEG2, take your time. No Hurry! :relaxed:

**Comment by JEG2** [comment]
:+1: 

I love the changes.

Super minor nit pick:  I prefer this style:

```rb
class HighLine  # in truth, I wish we could turn this into a namespace module only 
  module CustomErrors
    # ...
  end
end
```

For my reason, see the `Module.nesting` section [here](https://cirw.in/blog/constant-lookup).

**Comment by abinoam** [comment]
Now that @matugm has implemented all suggestions (the last from @JEG2 was on this last commit 
df22332) let's go merging!

**Pull request merged**
