### PR TITLE
Implement Menu's indices coloring - by Aregic

### PR DESCRIPTION
**Pull request by abinoam**
A rebased and review version of PR #193 
cc: @aregic @JEG2

### CODE REVIEW

**Comment by JEG2** [comment]
This seems great to me.  👍

**Comment by aregic** [comment]
Ops, I have made an error in the documentation:
```ruby
  menu.index_color  = :rgb_999999      # override default color of index
                                       # you can also use constants like :blue
```
This was the original way of setting the index_color, but since use_color is "static", I decided to make this "static" too (seemed more convenient during usage).

**Comment by abinoam** [comment]
Adding ```pronto``` output here just as reminder to me.
```
lib/highline/menu.rb:156 W: Is a writable attribute (Attribute)
lib/highline/menu.rb:490 W: Calls @items.map 4 times (DuplicateMethodCall)
lib/highline/menu.rb:490 W: Calls i.text 4 times (DuplicateMethodCall)
lib/highline/menu.rb:490 W: Has the variable name 'i' (UncommunicativeVariableName)
test/test_menu.rb:242 W: Calls @input.rewind 4 times (DuplicateMethodCall)
test/test_menu.rb:261 W: Calls @output.rewind 3 times (DuplicateMethodCall)
test/test_menu.rb:258 W: Calls @output.string 4 times (DuplicateMethodCall)
test/test_menu.rb:261 W: Calls @output.truncate(@output.rewind) 3 times (DuplicateMethodCall)
test/test_menu.rb:244 W: Calls @terminal.choose 4 times (DuplicateMethodCall)
test/test_menu.rb:248 W: Calls menu.choice "sample1" 4 times (DuplicateMethodCall)
test/test_menu.rb:249 W: Calls menu.choice "sample2" 4 times (DuplicateMethodCall)
test/test_menu.rb:250 W: Calls menu.choice "sample3" 4 times (DuplicateMethodCall)
test/test_menu.rb:246 W: Calls menu.index_color = index_color 4 times (DuplicateMethodCall)
test/test_menu.rb:238 W: Has approx 38 statements (TooManyStatements)
lib/highline/menu.rb:23 I: Use `attr_writer` to define trivial writer methods.
lib/highline/menu.rb:31 I: Use `attr_reader` to define trivial reader methods.
lib/highline/menu.rb:50 I: Assignment Branch Condition size for initialize is too high. [17.72/15]
lib/highline/menu.rb:50 I: Method has too many lines. [19/10]
lib/highline/menu.rb:490 I: Line is too long. [97/80]
lib/highline/menu.rb:490 I: Prefer `to_s` over string interpolation.
lib/highline/menu.rb:493 I: Prefer `to_s` over string interpolation.
lib/highline/menu.rb:493 I: Line is too long. [91/80]
lib/highline/menu.rb:495 I: Prefer `to_s` over string interpolation.
lib/highline/menu.rb:497 I: Prefer `to_s` over string interpolation.
lib/highline/menu.rb:497 I: Line is too long. [83/80]
test/test_menu.rb:238 I: Assignment Branch Condition size for test_index_with_color is too high. [63.79/15]
test/test_menu.rb:238 I: Method has too many lines. [63/10]
test/test_menu.rb:256 I: Use `\` instead of `+` or `<<` to concatenate those strings.
test/test_menu.rb:314 I: Use `\` instead of `+` or `<<` to concatenate those strings.
test/test_menu.rb:315 I: Use `\` instead of `+` or `<<` to concatenate those strings.
```

**Comment by abinoam** [comment]
I couldn't understand your comment about the documentation. Could you explain it in more details?

**Comment by abinoam** [comment]
By the way, I have made a minor change in the way it "gets" the color. It checks for a class set color and copy to an instance variable. So you can override it. Look at https://github.com/JEG2/highline/blob/4f2555133f08b7d2f7b43bf6610a52dbe5a96e8d/lib/highline/menu.rb#L74

**Comment by abinoam** [comment]
@aregic as we have a thumbs up from @JEG2 I'm merging it into master. Thank you very much for the PR! 👍

**Pull request merged**
