### PR TITLE
Release 3.0.0.pre.1

### PR DESCRIPTION
**Pull request by abinoam**
Ruby 2.7 is tagged End of Life (not even security maintenance) since this month.
We (Highline) traditionally try to maintain compatibility with old rubies.
But rubies bellow 2.7.1 lack "io/console" or they have incompatibilities.
(as discussed in PR #259)

So, this EOL of 2.7 signal to us that is time for us to move on.
People relying on old versions of Highline will probably face no problem with it.
But we will be free to start removing old code that is necessary only for
retro compatibility in newer versions.

First we're gonna release a 'pre' gem. So we have more time to testing and packing in more changes before the final release.

* PR #263 - Release 3.0.0.pre.1
  * Raise minimum Ruby version requirement to 3.0
* PR #262 - Do not call stty on non-tty (@kbrock)
* PR #260 / I #43 - Ctrl-U (erase line) handling (@abinoam, issue by @gutenye)
* PR #259 / I #236 - Handle Ctrl-C when Question#echo = false (@abinoam, @Fahhetah, issue by @aspyct)
* PR #258 / I #246 - Add validation class support (@abinoam, issue by @Joshfindit)
  * Make it dry-types compatible through the use of `#valid?`
  * Solve the multiple answers in one line problem with a combination of custom coercion (parser) and custom validation
* PR #257 / I #233 - Show Question#default hint for non String values (@abinoam, issue by @branch14)
  * Add Question#default_hint_show to allow disabling it.
* PR #256 / I #249 - Fix Array validation in Question#in (@abinoam, issue by @esotericpig)

### CODE REVIEW

**Comment by kbrock** [comment]
thanks @abinoam

**Comment by kbrock** [comment]
@abinoam do you have a timeline or outstanding issues before releasing the 3.0.0 final cut?

**Comment by abinoam** [comment]
Hi @kbrock thanks for pinging me. I was drowned by some personal things (nothing serious). But those things were taking a lot of my "free" time.

The good news are that I'll probably be more free from this month on. And your message made me put this on priority.

**Comment by abinoam** [comment]
> @abinoam do you have a timeline or outstanding issues before releasing the 3.0.0 final cut?

Basically I want to recheck all the code for parts that are there only for retro compatibility with old rubies.
It's not hard as I'm really used to the code base. But, I just have to sit and do it.

**Comment by kbrock** [comment]
> But, I just have to sit and do it.

There sure is not enough time out there, for sure.
Thank you for keeping this library up to date.
And thank you for the (unintended) reminder that I too have gems that need to be released

**Comment by abinoam** [comment]
Note to self: https://github.com/jruby/jruby/issues/3181

**Comment by kbrock** [comment]
does this mean that going towards `reline` has just upped in priority?

**Pull request merged**
