### PR TITLE
Show default value in menu 

### PR DESCRIPTION
**Pull request by fredrb**
Default option behaviour was already implemented, but not properly shown. The unit test added in this PR confirms this. (refer to #191). 

image

This appends the default value to the prompt, like in the image above.

### CODE REVIEW

**Comment by abinoam** [comment]
First of all I would like to say thank you very much for you PR!
It solves #191, doesn't it?

I have some tiny suggestions, please tell me if you agree with me.
1) Invert the order so you don't need to negate.
```diff
- return !@default.to_s.empty? ? "(#{@default}) " : ""
+ return @default.to_s.empty? ?  "" : "(#{@default}) "
```
2) Use the ```default``` accessor method defined in Question (parent class).
```diff
-  return @default.to_s.empty? ?  "" : "(#{@default}) 
+  return default.to_s.empty? ?  "" : "(#{default})
```
This will avoid an (inofensive but) annoying warning like:
```/highline/lib/highline/menu.rb:543: warning: instance variable @default not initialized```

3) The example in README.md is not working with ```:ruby``` but works with ```ruby```. 
Could you fix the README.md?

4) The example in README.md shows like:
```
1. ruby
2. python
3. perl
(ruby) Please choose your favorite programming language?
```
Which I think is acceptable. But, could you confirm that this was the intended behaviour? 
What about something like?
```
1. ruby
2. python
3. perl
(ruby)
Please choose your favorite programming language?
```

**Comment by fredrb** [comment]
Glad you appreciated!

- 1, 2: Agreed and fixed
- 3: Was a typo, actually, I meant to use the symbol `:ruby` not a string... Also fixed.
- 4: It was intended. Showing the default value on the same line is a personal preference. But it's up to you if we should use an extra line to show default value or not.

**Comment by abinoam** [comment]
Sorry, I have made a mistake. I have said that the README.md was wrong. But was the examples.
You have added the default option to the README but have used the Symbol again.
Just change the ```:ruby``` symbol into ```"ruby"``` string at both README and examples.
Am I right?

**Comment by fredrb** [comment]
Yes, it makes sense. But does it make a difference? `:ruby` is the symbol for "ruby" string, so either should work from my perspective (if I'm not wrong).

Did you get any errors testing the example?

**Comment by abinoam** [comment]
Hi @fredrb,

First time I have tested it I thought it has had an error with Symbol. 
I'm testing it now without errors.
Sorry for my mistake.

Thank you again for the PR.
Merging it!

**Comment by abinoam** [comment]
I have also updated the Changelog. 
It'll be at the next release.

**Pull request merged**
