### PR TITLE
Add MacOs, Windows, TruffleRuby and head branches to the GH Actions matrix

### PR DESCRIPTION
**Pull request by abinoam**
cc @petergoldstein

### CODE REVIEW

**Comment by abinoam** [comment]
Old rubies would probably pass if GitHub Actions respected `--without code_quality` bundle option.
But it seems that it *first* cache all gems and then *filter* from that.

**Comment by abinoam** [comment]
I give up the old rubies. For mental sanity! :smile: 
This PR improves github actions file to test against head branches, truffleruby, windows and macos.
It's good enough.
I'll merge it and make a new release (just for making people aware of the new Ruby version requirement).

**Comment by petergoldstein** [comment]
@abinoam You should updated the required rubies setting in the gemspec with the new version.  I'd frankly set the new version to something far more recent - say 2.7 or later

**Comment by abinoam** [comment]
I agree with you. But I prefer not to remove a version of the matrix as it's still working ok on it. As time passes and incompatibilities arise we will be "deprecating" these versions.

**Pull request merged**
