### PR TITLE
These files have no shebang and should not be executable

### PR DESCRIPTION
**Pull request by bdunne**

### CODE REVIEW

**Review by abinoam — APPROVED** [review]
Thank you for spotting the permissions issue and making the PR.

**Comment by abinoam** [comment]
Merged. I'll put it in the next release.

**Comment by bdunne** [comment]
Wow, that was fast.  Thanks @abinoam

**Comment by abinoam** [comment]
It was a clear PR. No work involved. And luckily I was online. Thanks again.

**Pull request merged**
