### PR TITLE
 Add new capital_letter option to menu index

### PR DESCRIPTION
**Pull request by Ana06**
To configure menu indexes we could use `:number`, `:letter` and `none` options. The `:letter` option uses lowercase letter. Add a new option `:capital_letter` which uses uppercase letter as indexes.

This code was written in **The Biggest Mobprogramming session ever** at [RubyConfBY 2019](https://rubyconference.by) (for details check commits descriptions).

Co-authored-by: @imikailoby
Co-authored-by: @alexneisc
Co-authored-by: @eduardoj
Co-authored-by: @tongueroo
Co-authored-by: @al13bash
Co-authored-by: @GenaMinenkov
Co-authored-by: @Tkarpesh
Co-authored-by: @pavelbonda
Co-authored-by: @shiroginne
Co-authored-by: @Kaddyluck
Co-authored-by: @vladyio
Co-authored-by: @DDKatch
Co-authored-by: @ddfreyne
Co-authored-by: @nbulaj
Co-authored-by: @dsalahutdinov
Co-authored-by: @foxweb
Co-authored-by: @vkalach
Co-authored-by: Dzmitry
Co-authored-by: @tongueroo
Co-authored-by: @ilyabyar
Co-authored-by: @ahrechushkin
Co-authored-by: Piotr Wasiak
Co-authored-by: @tenderlove
Co-authored-by: @Iharidla
Co-authored-by: @mrusakovich
Co-authored-by: @ktopolski
Co-authored-by: @k-rudy
Co-authored-by: Artyom
Co-authored-by: @in-hale
Co-authored-by: @bekasovoleg
Co-authored-by: @woarewe
Co-authored-by: @arnikasky
Co-authored-by: @goodniceweb
Co-authored-by: @a0s
Co-authored-by: @lucerion
Co-authored-by: @igorpolyakov
Co-authored-by: @fayriss
Co-authored-by: @ymatusevich
Co-authored-by: @fatpaher
Co-authored-by: Vlad 
Co-authored-by: @Kislak
Co-authored-by: Boris & Anton
Co-authored-by: @KarinaTiurina
Co-authored-by: @akryuda
Co-authored-by: @rtrv
Co-authored-by: @dimaalex
Co-authored-by: @kolesa
Co-authored-by: @allomov
Co-authored-by: @J0n1c
Co-authored-by: @dzhlobo
Co-authored-by: @oryzhko
Co-authored-by: @skyksandr
Co-authored-by: @dmitriy-kiriyenko

Thanks all of you for your participation in the session! :heart: There were many more people in the session than the ones who signed up as co-authors (250 vs 51). If you were in the session and you want to appear in the co-authors as well, fill the survey with the link I sent in the conference or write me. :wink: If any of the co-authors information is not correct, please let me know as well. :wink: 

picture
picture

### CODE REVIEW

**Comment by JEG2** [comment]
I'll leave this for @abinoam to merge, but I think this is so awesome!

**Comment by Ana06** [comment]
I have added 2 co-authors more. 53 authors, I think we are complete! :smile:

**Comment by abinoam** [comment]
AWESOME!!! AWESOME!!! I don't have words to express how cool I think these kind of sessions are!!! Tonight I'm gonna merge it and make a release. Thank you very much.

**Comment by abinoam** [comment]
I proudly inform you that your code is properly released at version 2.0.2.

See: https://rubygems.org/gems/highline/versions/2.0.2

Congratulation to all of you that participated in the session.
I hope you all have a long and pleasant run as a code contributor at the Ruby community.
There's tons of projects where your help will be valuable.

**Comment by Ana06** [comment]
@JEG2 @abinoam thanks for your nice words and for the release :heart_eyes_cat: Thanks also to everybody who participated in the mobprogramming session, to the RubyConfBY organizers/volunteers for the help during the session and with the setup and to my collages at @suse who helped me with the preparation of the talk :heart: :green_heart: :blue_heart: :purple_heart: :yellow_heart:

**Pull request merged**
